USE company;
SELECT * FROM EMP;
SELECT * FROM DEPT;
-- ---------------------- ASSIGNMENT QUIERIES (115) ------------------------

-- 1.DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMENT NAMES ENDING 'S'
	
    SELECT *
    FROM EMP
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM DEPT
                     WHERE DNAME LIKE '%S');

-- 2.QUERY TO DISPLAY THE EMPLOYEE NAMES WHO IS HAVING MAXIMUM SALARY IN DEPT NAME "ACCOUNTING".
	
    SELECT ENAME
    FROM EMP 
    WHERE SAL IN (SELECT MAX(SAL)
				  FROM EMP
                  WHERE DEPTNO IN (SELECT DEPTNO
								   FROM DEPT
                                   WHERE DNAME = 'ACCOUNTING'));
    
-- 3.QUERY TO DISPLAY THE DEPT NAME WHO IS HAVING HIGHEST COMMISSION.

	SELECT DNAME 
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM EMP
                     GROUP BY DEPTNO
                     HAVING MAX(COMM));
                     
-- 4. QUERY TO DISPLAY THE EMPLOYEE NAMES WHOSE DEPARTMENT NAME HAS 2ND CHARACTER AS 'O'.

	SELECT ENAME
    FROM EMP 
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM DEPT
                     WHERE DNAME LIKE '_O%');

-- 5. QUERY TO DISPLAY ALL THE EMPLOYEES WHOSE DEPT NUMBER IS SAME AS SCOTT.
	
    SELECT ENAME
    FROM EMP
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM EMP 
                     WHERE ENAME = 'SCOTT');
    
-- 6.QUERY TO DISPLAY ALL THE EMPLOYEES IN 'OPERATIONS AND ACCOUNTING' DEPT.
	
    SELECT ENAME
    FROM EMP
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM DEPT
                     WHERE DNAME IN ('OPERATIONS' , 'ACCOUNTING'));
                     
-- 7.LIST THE EMPLOYEES WHO HAS SALARY GREATER THAN MILLER
	
    SELECT ENAME
    FROM EMP
    WHERE SAL > (SELECT SAL
				 FROM EMP 
                 WHERE ENAME = 'MILLER');
    
-- 8. LIST DEPARTMENT NAME HAVING ATLEAST 3 SALESMAN

	SELECT DNAME
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM EMP
                     WHERE JOB = 'SALESMAN'
                     GROUP BY DEPTNO
                     HAVING COUNT(*) > 2);
                     
-- 9. DISPLAY THE DNAME OF AN EMPLOYEES WHO HAS NO REPORTING MANAGER.
	
    SELECT DNAME
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM EMP
                     WHERE MGR IS NULL);
    
-- 10. LIST ALL THE EMPLOYEES WHO ARE REPORTING TO JONES MANAGER.

	SELECT ENAME
    FROM EMP
    WHERE MGR = (SELECT MGR
				 FROM EMP
                 WHERE ENAME = 'JONES');
                 

-- 11. LIST EMPLOYEES FROM RESEARCH ACCOUNTING HAVING AT LEAST 2 REPORTING.
	
    SELECT ENAME 
    FROM EMP
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM DEPT
                     WHERE DNAME IN ('RESEARCH' , 'ACCOUNTING')) AND EMPNO IN ( SELECT MGR
																				FROM EMP
																				WHERE MGR IS NOT NULL
																				GROUP BY MGR
																				HAVING COUNT(*) > 1 );
                     
-- 12. DISPLAY THE DEPARTNAME OF THE EMPLOYEE WHOSE NAME DOES NOT STARTS WITH S AND SALARY BETWEEN 1500 TO 3000.
	
    SELECT DNAME 
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM EMP 
                     WHERE ENAME NOT LIKE 'S%' AND SAL BETWEEN 1500 AND 3000);
	
    
-- 13.DISPLAY LOCATION OF EMPLOYEE WHOSE SALARY IS MINIMUM SALARY BUT SALARY IS GREATER THAN 2000

	SELECT LOC 
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
					FROM EMP
					WHERE SAL IN (SELECT MIN(SAL)
								  FROM EMP
								  WHERE SAL > 2000));
                                  

-- 14. DISPLAY THE LOCATION OF AN EMPLOYEE IN ACCOUNTING DEPARTMENT.
	SELECT LOC
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM DEPT
                     WHERE DNAME = 'ACCOUNTING');
  
  	SELECT LOC
    FROM DEPT
    WHERE DNAME = 'ACCOUNTING';
	
                     
-- 15. DISPLAY THE DEPARTMENT‘S LOCATION THAT IS HAVING GREATER THAN FOUR EMPLOYEES IN IT.
	
	SELECT LOC
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM EMP
                     GROUP BY DEPTNO
                     HAVING COUNT(*) > 4);
    
-- 16. WRITE A QUERY TO DISPLAY ALL THE EMPLOYEE WHOSE JOB NOT SAME AS ALLEN AND SALARY IS GREATER THAN MARTIN.
	
		SELECT ENAME
        FROM EMP
        WHERE JOB NOT IN (SELECT JOB 
						 FROM EMP
                         WHERE ENAME = 'ALLEN') 
				AND
			SAL > (SELECT SAL
					FROM EMP
                    WHERE ENAME = 'MARTIN');
    
-- 17. DISPLAY ALL THE EMPLOYEES WHO IS HAVING LOCATION IS SAME AS ADAM'S MANAGER?
	
    SELECT *
    FROM EMP
    WHERE DEPTNO IN (SELECT DEPTNO
						FROM DEPT
						WHERE LOC IN(SELECT LOC
									FROM DEPT
									WHERE DEPTNO IN (SELECT DEPTNO
													FROM EMP
													WHERE EMPNO IN(SELECT MGR
																	FROM EMP
																	WHERE ENAME = 'ADAM'))));
                    
-- 18. DISPLAY THE JOB, MANAGER NUMBER OF EMPLOYEES WHO IS WORKING FOR JONES?
	SELECT JOB, MGR
    FROM EMP
    WHERE MGR IN (SELECT EMPNO
				 FROM EMP
                 WHERE ENAME = 'JONES');
                 
	SELECT E1.JOB , E1.MGR
    FROM EMP E1 JOIN EMP E2
    ON E1.MGR = E2.EMPNO
    WHERE E2.ENAME = 'JONES';
                 
-- 19. DISPLAY THE EMPLOYEE NAMES, HIGHER DATE, COMMISSION OF FORD'S MANAGER?
	
    SELECT ENAME, HIREDATE, COMM
    FROM EMP
    WHERE EMPNO IN (SELECT MGR
				FROM EMP
                WHERE ENAME = 'FORD');
                
	SELECT E2.ENAME, E2.HIREDATE , E2.COMM
    FROM EMP E1 JOIN EMP E2
    ON E1.MGR = E2.EMPNO
    WHERE E1.ENAME = 'FORD';
    
    
-- 20. DISPLAY THE NUMBER OF EMPLOYEES WHO ARE GETTING SALARY LESS THAN THE BLAKE'S MANAGER
	
    SELECT COUNT(*) AS COUNT
    FROM EMP
    WHERE SAL < (SELECT SAL
				  FROM EMP
                  WHERE EMPNO IN (SELECT MGR
									FROM EMP
									WHERE ENAME = 'BLAKE'));

	SELECT COUNT(*)
    FROM EMP
    WHERE SAL < (SELECT E2.SAL
				FROM EMP E1 JOIN EMP E2
				ON E1.MGR = E2.EMPNO
				WHERE E1.ENAME = 'BLAKE');

-- 21. LIST EMPLOYEES WHO LOCATED IN CHICAGO AND THEIR COMMISSION IS ZERO.
	
    SELECT ENAME
    FROM EMP
    WHERE DEPTNO IN (SELECT DEPTNO
						FROM DEPT
						WHERE LOC = 'CHICAGO') AND COMM = 0;
                        
    SELECT E.ENAME
    FROM EMP E JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
    WHERE D.LOC = 'CHICAGO' AND E.COMM = 0;
    
-- 22. LIST EMPLOYEES WHO WORK FOR SALES DEPARTMENT AND THEIR SALARY GREATER THAN AVERAGE SALARY OF THEIR DEPARTMENT.
	
    SELECT E.ENAME
    FROM EMP E JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
    WHERE DNAME = 'SALES' AND SAL > (SELECT AVG(E.SAL)
									 FROM EMP E JOIN DEPT D
                                     ON E.DEPTNO = D.DEPTNO
                                     WHERE D.DNAME = 'SALES');
    
	SELECT ENAME 
    FROM EMP
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM DEPT
                     WHERE DNAME = 'SALES')
			AND
		 SAL > (SELECT AVG(SAL)
				FROM EMP
                WHERE DEPTNO IN (SELECT DEPTNO
								 FROM DEPT
                                 WHERE DNAME = 'SALES'));
                                 
-- 23. LIST EMPLOYEES WHO ARE WORKING IN RESEARCH DEPARTMENT AND THEY ARE MANAGER.

	SELECT E.ENAME
    FROM EMP E JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
    WHERE D.DNAME = 'RESEARCH' AND E.JOB = 'MANAGER';
    
    
    SELECT ENAME 
    FROM EMP
    WHERE JOB = 'MANAGER'
    AND
    DEPTNO IN (SELECT DEPTNO
			   FROM DEPT
               WHERE DNAME = 'RESEARCH');

-- 24. DISPLAY DEPARTMENT NAME OF THE EMPLOYEES WHO EARN COMMISSION.
	
    SELECT DISTINCT D.DNAME
    FROM EMP E JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
    WHERE E.COMM > 0;
    
    SELECT DNAME
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM EMP 
                     WHERE COMM > 0);

-- 25. DISPLAY DEPARTMENT NAME OF THE EMPLOYEE WHO EARN MAXIMUM SALARY AND HAVE NO REPORTING MANAGER.

	SELECT D.DNAME 
    FROM EMP E JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
    WHERE SAL IN (SELECT MAX(SAL)
				  FROM EMP)
			AND
		 MGR IS NULL;
         
         
	SELECT DNAME 
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM EMP
                     WHERE SAL IN (SELECT MAX(SAL)
									FROM EMP) 
							AND
						MGR IS NULL);

-- 26. DISPLAY EMPLOYEE DETAILS WHO ARE REPORTING TO BLAKE AND HAVE COMMISSION.

	SELECT *
    FROM EMP
    WHERE MGR IN (SELECT EMPNO
				  FROM EMP
                  WHERE ENAME = 'BLAKE')
			AND
		COMM > 0;

	SELECT E.*
    FROM EMP E JOIN EMP M
    ON E.MGR = M.EMPNO
    WHERE M.ENAME = 'BLAKE' AND E.COMM > 0;

-- 27. LIST ALL THE DEPT NAME AND LOC OF ALL THE SALESMAN MANAGER-MANAGER'S

	SELECT DNAME, LOC
    FROM DEPT
    WHERE DEPTNO IN (SELECT DEPTNO
					 FROM EMP
                     WHERE EMPNO IN (SELECT MGR
									 FROM EMP
                                     WHERE JOB = 'SALESMAN'));
                           
	SELECT DISTINCT D.DNAME, D.LOC
	FROM EMP E JOIN EMP M
    ON E.MGR = M.EMPNO
	JOIN DEPT D
    ON M.DEPTNO = D.DEPTNO
	WHERE E.JOB = 'SALESMAN';

-- 28. LIST THE EMPLOYEE DEPTNAME AND LOC OF ALL THE EMPLOYEES WHO ARE CLERK,
--     REPORTING TO BLAKE AND SALARY IS LESSER THAN MARTIN SALARY

	SELECT DNAME, LOC
    FROM DEPT
    WHERE DEPTNO IN ( SELECT DEPTNO
					 FROM EMP
                     WHERE JOB = 'CLERK'
                     AND  MGR IN (SELECT EMPNO
								  FROM EMP
								  WHERE ENAME IN ('BLAKE'))
					 AND SAL < (SELECT SAL 
								FROM EMP
                                WHERE ENAME = 'MARTIN'));

	
-- 29. LIST THE EMPLOYEES WHO DOES NOT DIRECTLY REPORT TO PRESIDENT, HAVE
--     COMMISSION AND SALARY MORE THAN MAX SALARY OF ALL THE CLERK WITHOUT
--     USING NULL OR NOT NULL
	
    SELECT *
    FROM EMP
    WHERE MGR NOT IN (SELECT EMPNO
						FROM EMP
                        WHERE JOB = 'PRESIDENT') AND COMM > 0 AND SAL > (SELECT MAX(SAL)
																		FROM EMP
                                                                        WHERE JOB = 'CLERK');
    
-- 30. LIST THE EMPLOYEES WHO JOINED AFTER 2 YEARS OF FIRST EMPLOYEE OF THE
--     COMPANY AND MORE THAN BLAKE SALARY
	
    SELECT ENAME
    FROM EMP
    WHERE HIREDATE > (SELECT MIN(HIREDATE) + 730
					  FROM EMP)
		AND SAL > (SELECT SAL
				FROM EMP
                WHERE ENAME = 'BLAKE');
		
-- 31. DISPLAY LOCATION OF ALL THE EMPLOYEES WHO REPORTING TO BLAKE

	SELECT D.LOC
    FROM EMP E JOIN EMP M
    ON E.MGR = M.EMPNO
    JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
    WHERE M.ENAME = 'BLAKE';
    

-- 32. LIST ALL THE EMPLOYEES WHOSE JOB IS SAME AS JONES AND THEIR SALARY
--     LESSER THAN SCOTT

-- 33. DISPLAY ALL THE EMPLOYEES OF DEPARTMENT 30, 20 WITH THEIR ANNUAL SALARY
--     AND HAVING ATLEAST 3 EMPLOYEES

-- 34. DISPLAY ALL THE EMPLOYEES WHO EARN LESS THAN ANY OF THE SALESMAN

-- 35. DISPLAY ALL THE EMPLOYEES WHO ARE JOINED BEFORE THE LAST PERSON

-- 36. FIND 3RD MINIMUM SALARY IN THE EMPLOYEE TABLE

-- 37. DISPLAY ALL THE EMPLOYEES WHO ARE EARNING MORE THAN ANY OF THE MANAGER

-- 38. LIST EMPLOYEES WHO JOINED AFTER 4 YEARS OF 1ST EMPLOYEE OF THE COMPANY
--     AND LESS THAN BLAKE SALARY

-- 39. DISPLAY THE DEPARTMENT INFORMATION OF EMPLOYEE WHO IS WORKING FOR NEW YORK LOCATION

-- 40. DISPLAY LOCATION OF EMPLOYEES, WHOSE NAME DOESN'T START WITH A AND
--     SALARY BETWEEN 1000 AND 3000

-- 41. DISPLAY DEPARTMENT NAME OF ALL THE EMPLOYEES WHO ARE REPORTING TO BLAKE

-- 42. DISPLAY MARTIN'S MANAGER'S MANAGER'S DEPARTMENT NAME AND LOCATION

-- 43. DISPLAY THE MANAGER NUMBER, JOB AND DEPARTMENT NUMBER FOR THOSE WHO
--     DON'T HAVE COMMISSION IN THE LOCATION CHICAGO OR DALLAS

-- 44. DISPLAY THE EMPLOYEE DETAILS WITH THEIR ANNUAL SALARY WHO EARN MAXIMUM COMMISSION

-- 45. DISPLAY ALL THE EMPLOYEE WHOSE DEPARTMENT IS SALES AND WHO IS EARNING
--     SOME COMMISSION (I.E COMMISSION IS NOT NULL OR ZERO) AND WHO IS HIRED
--     BEFORE THE LAST PERSON HIRED

-- 46. DISPLAY ALL THE DEPARTMENT NAMES FOR WARD'S MANAGER'S MANAGER

-- 47. DISPLAY DEPARTMENT NAMES OF EMPLOYEES WHOSE SALARY IS GREATER THAN
--     AVERAGE SALARY OF ALL THE CLERK'S

-- 48. DISPLAY THE LAST EMPLOYEE RECORD WITH 25% HIKE IN SALARY

-- 49. DISPLAY THE DEPARTMENT NUMBER WHO WORKING IN SALES DEPARTMENT AND THEY
--     ARE MANAGER